CREATE TABLE IF NOT EXISTS countries (
    country_id int
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    country_name text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS cities (
    city_id int
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    city_name text NOT NULL,
    country_id int NOT NULL
        REFERENCES countries,

    UNIQUE (country_id, city_name)
);

CREATE TABLE IF NOT EXISTS addresses (
    address_id int
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    postal_code text NOT NULL,
    address text NOT NULL,
    city_id int NOT
        NULL REFERENCES cities,

    UNIQUE (postal_code, address, city_id)
);

CREATE TABLE IF NOT EXISTS hotels (
    hotel_id int
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    hotel_name text NOT NULL,
    star_rating smallint NOT NULL
        DEFAULT 0
        CHECK (star_rating BETWEEN 0 AND 5)
);

CREATE TABLE IF NOT EXISTS room_types (
    room_type_id int
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    type_name text NOT NULL,
    room_capacity smallint NOT NULL
        DEFAULT 1
        CHECK ( room_capacity BETWEEN 1 AND 20),

    UNIQUE (type_name, room_capacity)
);

CREATE TABLE IF NOT EXISTS rooms (
    room_id int
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    hotel_id int NOT NULL
        REFERENCES hotels,
    room_number int NOT NULL,
    room_type_id int NOT NULL
        REFERENCES room_types,

    UNIQUE (hotel_id, room_number)
);

CREATE TABLE IF NOT EXISTS clients (
    client_id int
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    first_name text NOT NULL,
    last_name text NOT NULL,
    phone_number text,
    email text
);

CREATE TABLE IF NOT EXISTS reservations (
    reservation_id int
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    room_id int NOT NULL
        REFERENCES rooms,
    reservation_period daterange NOT NULL,
    client_id int NOT NULL
        REFERENCES clients
);
